- .github/workflows/publish.yml
At this time, the `helm/chart-releaser-action` doesn't automatically add the required Helm repositories, for security reasons. We need to manually add the needed repositories before running the action.
> Add dependencies to `publish` GH action

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/Chart.yaml
- charts/deepgram-self-hosted/README.md
- charts/deepgram-self-hosted/templates/api/api.deployment.yaml
- charts/deepgram-self-hosted/templates/engine/engine.deployment.yaml
- charts/deepgram-self-hosted/templates/license-proxy/license-proxy.deployment.yaml
API, Engine, and License Proxy containers require a container restart in order to load a new set of configuration values.
This change adjusts the Helm chart to automatically restart these containers if the underlying ConfigMap has changed. See [Helm docs](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) for details.
> Reload deployments when underlying configmaps change

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- charts/deepgram-self-hosted/README.md
- charts/deepgram-self-hosted/README.md.gotmpl
- charts/deepgram-self-hosted/templates/api/api.deployment.yaml
- charts/deepgram-self-hosted/templates/engine/engine.deployment.yaml
- charts/deepgram-self-hosted/templates/license-proxy/license-proxy.deployment.yaml
- charts/deepgram-self-hosted/values.yaml
There are cases where the Helm chart may not require credentials to access the Deepgram container image repositories hosted on Quay. This PR removes the firm requirement to include these credentials as a pull secret for pulling container images.
For example, a client may pull the images from Quay manually and push them into a private company repository that meets certain security or scanning requirements. Credentials to that private repo may be pre-configured in the cluster, so the pull secret shouldn't be mandatory. 
Another case is if a [Docker proxy](https://docs.docker.com/network/proxy/) is being used and credentials are supplied in the proxy. Then the credentials don't need to be exposed directly in the cluster with this Helm chart.
Resolves #14.
> Make image pull secret optional

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/templates/volumes/aws/efs.pvc.yaml
This change fixes a template issue when using AWS EFS as the storage for self-hosted deployments
> [ISSUE-27] Fix EFS Storage Class Mismatch with Name Prefix

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- charts/deepgram-self-hosted/CHANGELOG.md
This change improves the DevOps portion of this repo in the following ways:
- Adds a standardized Pull Request template
- Adds a CI check to ensure that the Helm chart appVersion is not updated without also bumping the chart Version
- Adds a CI check to ensure that the chart changelog is updated if the chart is updated
- Improves reliability of the publish GH action
- The `chart-releaser-action` will attempt to run if git detects any changes at all in the chart directory. 
- This means if a change was merged, but we aren't yet cutting a release by bumping the version number, git will still detect changes and so `chart-releaser-action` will attempt to run.
- It will create a tarball and attempt to create a release, but under the same version as the current/latest version. GitHub will …
> CI and PR template improvements

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/templates/api/api.deployment.yaml
- charts/deepgram-self-hosted/templates/engine/engine.deployment.yaml
- charts/deepgram-self-hosted/templates/license-proxy/license-proxy.deployment.yaml
This PR removes a dangling `or` directive in between another `or` statement that caused an error when `serviceAccount.create` was set to false and the outer `or` statement continued to try and evaluate the next condition.
Fixes #25 
- Verified behavior locally with `helm template`. Was able to reproduce error from #25 before fix, and error is resolved after the fix.
> Fix malformed `or` statement with serviceAccounts

- .github/workflows/ci.yml
When submitting #29, I noticed the [CI action succeeded but had errors](https://github.com/deepgram/self-hosted-resources/actions/runs/9941681484/job/27461328089#step:9:23). These errors didn't occur locally when running with `act`. After digging into it, I found [this issue](https://github.com/actions/checkout/issues/296) with the `checkout` GitHub action that seems to suggest we need to explicitly define the remote for $GITHUB_BASE_REF for it to work. 
- As this action is specific to remote GH actions and I can't reproduce locally, I'm not sure how to test locally
> Add explicit remote when using $GITHUB_BASE_REF

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/README.md
- charts/deepgram-self-hosted/templates/api/api.deployment.yaml
- charts/deepgram-self-hosted/templates/engine/engine.deployment.yaml
- charts/deepgram-self-hosted/templates/license-proxy/license-proxy.deployment.yaml
- charts/deepgram-self-hosted/values.yaml
Allow specifying custom annotations on Deployment templates for organizing clusters.
- Verified that values are respected by running `helm template` locally
> Allow custom annotations to deployments

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/Chart.yaml
- charts/deepgram-self-hosted/README.md
- charts/deepgram-self-hosted/templates/api/api.config.yaml
- charts/deepgram-self-hosted/templates/engine/engine.config.yaml
- charts/deepgram-self-hosted/values.yaml
- common/license_proxy_deploy/api.toml
- common/standard_deploy/api.toml
- docker/docker-compose.license-proxy.yml
- docker/docker-compose.standard.yml
- podman/podman-compose.license-proxy.yml
- podman/podman-compose.standard.yml
- Update Helm chart and other resources to `release-240725` of Deepgram containers
- Expose feature flags for three new self-hosted beta features: pre-recorded entity detection, improved pre-recorded  redaction, and improved streaming formatting
- Removed certain Helm options for feature flags that should always be enabled
> July 2024 Deepgram product release update

- docker/docker-compose.license-proxy.yml
- docker/docker-compose.standard.yml
- podman/podman-compose.license-proxy.yml
- podman/podman-compose.standard.yml
Remove Compose file version keys, as they are [now deprecated](https://github.com/compose-spec/compose-spec/blob/main/04-version-and-name.md) and emit a warning when used.
> remove compose file versions

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/samples/03-basic-setup-onprem.yaml
The onprem sample file has a typo that wrongly suggests the `engine.modelManager.volumes.customVolumeClaim.name` should be a `PersistentVolume` instead of a `PersistentVolumeClaim`. This PR addresses that.
- [-] I have tested my changes in my local self-hosted environment
> Fix onprem sample file comment

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/samples/01-basic-setup-aws.values.yaml
- charts/deepgram-self-hosted/samples/02-basic-setup-gcp.yaml
- charts/deepgram-self-hosted/samples/03-basic-setup-onprem.yaml
Update sample files to fix an issue with sample files. The sample command for creating a Kubernetes Secret to store Quay credentials would fail in certain situations, most commonly on MacOS with Docker Desktop installed.
Previous command:
```
kubectl create secret generic dg-regcred \
--from-file=.dockerconfigjson=$HOME/.docker/config.json \
--type=kubernetes.io/dockerconfigjson
```
This previous command used `--from-file` with the user's Docker configuration file. When using MacOS with Docker Desktop installed, Docker Desktop will store credentials in Apple Keychain, leaving the configuration file empty. The k8s secret creation then results in an empty secret being created, as it doesn't attempt to pull the secret from Apple Keychain.
This PR changes the default command to work …
> Fix sample k8s secret command for quay credentials

- .github/workflows/ci.yml
- README.md
- diagnostics/README.md
- diagnostics/dg_log_parser.sh
- diagnostics/dg_validate_nvidia_setup.sh
Add a couple of helper diagnostic scripts for common troubleshooting situations. See `/diagnostics/README.md` for details on each added script.
- Tested each script with a variety of environments and log files with detectable errors
> New diagnostics dir

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/samples/01-basic-setup-aws.cluster-config.yaml
- charts/deepgram-self-hosted/samples/01-basic-setup-aws.values.yaml
Previously, Amazon did not offer any official AMIs that included a recent version of the NVIDIA driver/toolkit and updated versions of system packages. The community demand for this has grown such that two weeks ago AWS released [an EKS accelerated AMI] based on Amazon Linux 2023. This means we now have an officially supported AWS AMI with bundled drivers and toolkits that is compatible with Deepgram workloads.
This PR updates the sample directory to use these new AMIs, and adjust the AWS example `values.yaml` file to no longer manually install NVIDIA drivers with the GPU operator Helm Chart. 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of …
> Use AWS accelerated AMIs

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/templates/volumes/aws/efs-model-download.job.yaml
The AWS model download job is coupled with the Engine deployment as currently implemented, and uses the same affinity. This fixes a scheduling issue by also adding the Engine tolerations block to that model download job, to avoid being blocked by node taints.
Resolves #48
> Add tolerations for model download job

- docker/docker-compose.license-proxy.yml
- docker/docker-compose.standard.yml
- podman/podman-compose.license-proxy.yml
- podman/podman-compose.standard.yml
Resource limits can be an effective way to prevent containers from starving eachother. 
However, in a single VM running multiple Deepgram containers (most common use case with Docker), allowing containers to have more ebb and flow in their resource usage can lead to greater performance and easier management. 
This also prevents artificially low limits being enforced when these templates are used for more powerful instance types, but users forget to increase the default limits.
- Updated best practice on Compose templates
> Remove resource limits on Compose file templates

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/values.yaml
The x100 multiplier in the existing metrics is not compatible with the scaling ratio from 0.0 to 1.0 in the chart.  I'm removing the multiplier to make it consistent with the comments in the values file for scaling.auto.engine.metrics.requestCapacityRatio
This could be a breaking change for any users that have changed the ratio to use a scale from 0 to 100 rather than changing the custom metrics.
What types of changes does your code introduce to the Deepgram self-hosted resources?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- Please describe your …
> Fix Helm Chart Prometheus Adapter Metrics

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/README.md
- charts/deepgram-self-hosted/templates/api/api.deployment.yaml
- charts/deepgram-self-hosted/templates/engine/engine.deployment.yaml
- charts/deepgram-self-hosted/values.yaml
This PR fixes securityContext template references in the API and Engine deployment templates. The templates were referencing .Values.licenseProxy.securityContext instead of their respective .Values.api.securityContext and .Values.engine.securityContext values.
What types of changes does your code introduce to the Deepgram self-hosted resources?
- I used this chart to install Deepgram in our non-prod k8s cluster, verified correct deployment config and that the application operates correctly
> Fixes Issue 79 -- Incorrect securityContext template references in API and Engine deployments

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/templates/engine/engine.deployment.yaml
Allow `null` or an empty string to be set for the `engine` CPU and memory limits to avoid setting limits on these containers.
Resolves https://github.com/deepgram/self-hosted-resources/issues/92
What types of changes does your code introduce to the Deepgram self-hosted resources?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- Tested by deploying from local chart, upgrading from a previously deployed chart.
- Values files updated to set:
```
engine:
resources:
limits:
cpu: null
memory: ""
```
- `helm diff` output
```
resources:
requests:
memory: …
```
> Support removing resource limits on engine pods

- charts/deepgram-self-hosted/CHANGELOG.md
- charts/deepgram-self-hosted/Chart.yaml
- charts/deepgram-self-hosted/README.md
What types of changes does your code introduce to the Deepgram self-hosted resources?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- Please describe your testing setup and methodology here
> Helm release 0.20.0
